### ISSUE TITLE
Contributing Guidelines?

### ISSUE THREAD

**Issue by Blackglade** [hyplabs/AlgoSwap#5]
Hi,

Interested in helping out with this project but didn't see any contributing guidelines? Wanted to work on the frontend React App you guys have set up. Is there any guidelines/design system/overall look you are aiming for? Also wasn't sure the proper way to reach out (ie: Github Issue or via direct email).

**Comment by Uberi** [comment]
Hi @Blackglade, thanks for reaching out! Currently, we don't have anything in particular for design besides "functionally similar to Uniswap-like DEXs".

What would you like to see in AlgoSwap? We're not too set on the details, so let us know if you see something specific you'd like to help with!

**Comment by Derekbrenner** [comment]
Hey there,  If you need some design work I would like to help out.
